### ISSUE TITLE
/api/account-info method invocation fails.

### ISSUE THREAD

**Issue by dvponomarev** [yandex-money/yandex-money-sdk-java#30]
Invocation of /api/account-info method fails both on prod and demo servers.

Library: com.yandex.money.api:yandex-money-sdk-java:5.1.6

1) prod server: https://money.yandex.ru: fails on missing balanceDetails.
```
--> POST https://money.yandex.ru/api/account-info HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 0
Cache-Control: no-cache
Accept-Language: ru
Authorization: Bearer xxx.xxx

--> END POST (0-byte body)
<-- HTTP/1.1 200 OK (438ms)
Date: Fri, 19 Aug 2016 10:36:10 GMT
Content-Type: application/json;charset=UTF-8
Connection: keep-alive
Keep-Alive: timeout=120
Vary: Accept-Encoding
Cache-Control: no-cache
Set-Cookie: TS01ca9aab=01f3111baf647fe1851be117f3ab18b9b1690f86f2823a62ad4be8b5c6b5733c1dcbb2976a; Path=/
Transfer-Encoding: chunked
OkHttp-Sent-Millis: 1471602970540
OkHttp-Received-Millis: 1471602970590

{"account":"xxx","balance":0.00,"currency":"643","account_type":"personal","identified":false,"account_status":"anonymous"}
<-- END HTTP (135-byte body)

java.lang.NullPointerException: balanceDetails is null
	at com.yandex.money.api.utils.Common.checkNotNull(Common.java:49)
	at com.yandex.money.api.methods.AccountInfo$Builder.setBalanceDetails(AccountInfo.java:235)
	at com.yandex.money.api.typeadapters.AccountInfoTypeAdapter.deserialize(AccountInfoTypeAdapter.java:117)
	at com.yandex.money.api.typeadapters.AccountInfoTypeAdapter.deserialize(AccountInfoTypeAdapter.java:55)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at com.yandex.money.api.typeadapters.BaseTypeAdapter.fromJson(BaseTypeAdapter.java:55)
	at com.yandex.money.api.net.BaseApiRequest.parseResponse(BaseApiRequest.java:79)
	at com.yandex.money.api.net.OAuth2Session.parseResponse(OAuth2Session.java:155)
	at com.yandex.money.api.net.OAuth2Session.execute(OAuth2Session.java:73)
```
2) demo server: https://demomoney.yandex.ru: server returns incorrect currency code 10643.
```
--> POST https://demomoney.yandex.ru/api/account-info HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 0
Cache-Control: no-cache
Accept-Language: ru
Authorization: Bearer xxx.xxx

--> END POST (0-byte body)
<-- HTTP/1.1 200 OK (319ms)
Date: Fri, 19 Aug 2016 11:04:24 GMT
Content-Type: application/json;charset=UTF-8
Connection: keep-alive
Keep-Alive: timeout=120
Vary: Accept-Encoding
Cache-Control: no-cache
Set-Cookie: TS019d3b22=01a1a1e3913fb944846ac9ab9fb641a261b045230bf4306641b008c319fce4c97a66e723e8; Path=/
Transfer-Encoding: chunked
OkHttp-Sent-Millis: 1471604664774
OkHttp-Received-Millis: 1471604664836

{"account":"xxx","balance":100.00,"currency":"10643","identified":false,"account_type":"personal","account_status":"anonymous","balance_details":{"total":100.00,"available":100.00}}
<-- END HTTP (191-byte body)

java.lang.NullPointerException: currency is null

	at com.yandex.money.api.utils.Common.checkNotNull(Common.java:49)
	at com.yandex.money.api.methods.AccountInfo$Builder.setCurrency(AccountInfo.java:199)
	at com.yandex.money.api.typeadapters.AccountInfoTypeAdapter.deserialize(AccountInfoTypeAdapter.java:113)
	at com.yandex.money.api.typeadapters.AccountInfoTypeAdapter.deserialize(AccountInfoTypeAdapter.java:55)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at com.yandex.money.api.typeadapters.BaseTypeAdapter.fromJson(BaseTypeAdapter.java:55)
	at com.yandex.money.api.net.BaseApiRequest.parseResponse(BaseApiRequest.java:79)
	at com.yandex.money.api.net.OAuth2Session.parseResponse(OAuth2Session.java:155)
	at com.yandex.money.api.net.OAuth2Session.execute(OAuth2Session.java:73)
```

**Comment by yasevich** [comment]
В первом случае сервер всегда должен возвращать объект `balanceDetails`. Отсутствие его в ответе можно считать ошибкой.

Во втором случае, если приходит неизвестная код валюты, то в объекте `AccountInfo` поле `currency` должно иметь значение по умолчанию `Currency.RUB`.
